import { type Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { Toaster } from "@/components/ui/sonner";
import { AuthHeader } from "@/components/auth-header";
import Authenticated from "./authenticated";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <Providers>
        <Authenticated>
        <html lang="en" className="h-full">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}
          >
            <AuthHeader />
            {children}
            <Toaster />
            </body>
          </html>
        </Authenticated>
      </Providers>
    </ClerkProvider>
  );
}
